# permissions for end users to edit digitalaideploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digitalaideploy-editor-role
rules:
- apiGroups:
  - xld.digital.ai
  resources:
  - digitalaideploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xld.digital.ai
  resources:
  - digitalaideploys/status
  verbs:
  - get
