
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - xld.digital.ai
  resources:
  - digitalaideploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xld.digital.ai
  resources:
  - digitalaideploys/finalizers
  verbs:
  - update
- apiGroups:
  - xld.digital.ai
  resources:
  - digitalaideploys/status
  verbs:
  - get
  - patch
  - update
