apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: xld-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DigitalaiDeploy is the Schema for the digitalaideploys API
      displayName: Digitalai Deploy
      kind: DigitalaiDeploy
      name: digitalaideploys.xld.digital.ai
      version: v1alpha1
  description: Digital.ai Deploy Kubernetes Operator
  displayName: Digital.ai Deploy Kubernetes Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Digital.ai Deploy
  links:
  - name: Xld Operator
    url: https://xld-operator.domain
  maturity: alpha
  provider:
    name: xld-operator
    url: https://xebialabs.github.io/xl-deploy-kubernetes-operator
  version: 0.0.0
